package com.idzodev.pokemonapp.domain.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.idzodev.pokemonapp.domain.entities.MainEntity;

import com.idzodev.pokemonapp.domain.entities.MainEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mainEntityDaoConfig;

    private final MainEntityDao mainEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mainEntityDaoConfig = daoConfigMap.get(MainEntityDao.class).clone();
        mainEntityDaoConfig.initIdentityScope(type);

        mainEntityDao = new MainEntityDao(mainEntityDaoConfig, this);

        registerDao(MainEntity.class, mainEntityDao);
    }
    
    public void clear() {
        mainEntityDaoConfig.getIdentityScope().clear();
    }

    public MainEntityDao getMainEntityDao() {
        return mainEntityDao;
    }

}
