package com.idzodev.pokemonapp.domain.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MAIN_ENTITY".
 */
public class MainEntity {

    private Long id;
    private String name;
    private Integer icon;
    private Integer power;
    private Integer type;
    private Double latitude;
    private Double longitude;

    // KEEP FIELDS - put your custom fields here
    public static final int TYPE_POKEMON = 1;
    public static final int TYPE_ZOMBI = 2;
    // KEEP FIELDS END

    public MainEntity() {
    }

    public MainEntity(Long id) {
        this.id = id;
    }

    public MainEntity(Long id, String name, Integer icon, Integer power, Integer type, Double latitude, Double longitude) {
        this.id = id;
        this.name = name;
        this.icon = icon;
        this.power = power;
        this.type = type;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIcon() {
        return icon;
    }

    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    public Integer getPower() {
        return power;
    }

    public void setPower(Integer power) {
        this.power = power;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
